apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-dbaas
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-dbaas
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      The configuration-dbaas configuration provides an example abstraction to
      provision multi-cloud database instances.
    meta.crossplane.io/readme: |
      The configuration-dbaas bundles a single API that allows unified
      multi-cloud provisioning of fully managed database instances. Save time
      and improve reliability by deploying the most popular database services
      using the same consistent Claim spec.
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-database
      # renovate: datasource=github-releases depName=upbound/configuration-aws-database
      version: "v0.8.0"
    - configuration: xpkg.upbound.io/upbound/configuration-azure-database
      # renovate: datasource=github-releases depName=upbound/configuration-azure-database
      version: "v0.9.0"
    - configuration: xpkg.upbound.io/upbound/configuration-gcp-database
      # renovate: datasource=github-releases depName=upbound/configuration-gcp-database
      version: "v0.2.0"
