apiVersion: dbaas.upbound.io/v1alpha1
kind: XSQLInstance
metadata:
  name: configuration-dbaas-azure-mysql
spec:
  parameters:
    provider: azure
    region: westus2
    engine: mysql
    engineVersion: "10.3"
    storageGB: 32
    passwordSecretRef:
      namespace: default
      name: mysqlsecretazure
      key: password
  writeConnectionSecretToRef:
    name: configuration-dbaas-azure-mysql
    namespace: default
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: mysqlsecretazure
  namespace: default
type: Opaque
