apiVersion: dbaas.upbound.io/v1alpha1
kind: XSQLInstance
metadata:
  name: configuration-dbaas-aws-postgresql
spec:
  parameters:
    provider: aws
    region: us-west-2
    engine: postgres
    engineVersion: "16.3"
    storageGB: 5
    passwordSecretRef:
      namespace: default
      name: psqlsecretaws
      key: password
  writeConnectionSecretToRef:
    name: configuration-dbaas-aws-postgresql
    namespace: default
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: psqlsecretaws
  namespace: default
type: Opaque
